### ISSUE TITLE
Force push

### ISSUE THREAD

**Issue by PssbleTrngle** [EndBug/add-and-commit#100]
This is not a bug report but a simple question.
Is it possible to tell the action to force push?

**Comment by EndBug** [comment]
Hi
No, at the moment it's not possible, but it would be a good idea to add it. I'll take a look at it as soon as I have the time to.

Also, this would fix #99

**Comment by EndBug** [comment]
@all-contributors please add @PssbleTrngle for their idea

**Comment by EndBug** [comment]
Here we go: I've just published a new version that allows you to set the arguments of the `git push` command used by the action.
You can find more info in the README; the new version is `v6.2.0` (also `v6` and `latest`)

I'll close the issue for now, feel free to tell me if you find any issue with it ;)

**Comment by barrettj12** [comment]
So how can you actually tell git to force push? I tried setting the option
```yaml
push: origin ${branch input} --force --set-upstream
```
but this doesn't seem to work.

**Comment by EndBug** [comment]
@barrettj12 That's weird, could you open a bug report issue (fill in all the fields) so that we can work it out?

**Comment by barrettj12** [comment]
@EndBug: I've opened a new issue #320
