### ISSUE TITLE
It is not possible to push a tag without changing files

### ISSUE THREAD

**Issue by agersant** [EndBug/add-and-commit#106]
If no files in the repository has been changed or touched, the action will do nothing, even when the `tag` option is used.

My use case for this is I have a workflow which merges from a staging branch to a production branch, a build to some third party (without changing any local files), and should add a tag which indicates that this commit is what was sent to the third party.

Thank you!

**Comment by EndBug** [comment]
Hi
I think I understand your issue, but here's the problem: the `tag` option is intended to add a tag to the commit the action just created. That means that if the action doesn't create any commit (like if there are no file changes) then in its perspective there's no commit to tag. 
If you're merging two branches, then you're supposed to tag that commit. 

I'd like to keep this action focused on committing changes, the `tag` option is just something extra: it's better if you look for some other action that will let you tag those commits, or maybe just run git commands. 

Let me know if you need anything else ;)

**Comment by agersant** [comment]
No problem, thanks for replying!
