### ISSUE TITLE
From docker to node

### ISSUE THREAD

**Issue by jactor-rises** [EndBug/add-and-commit#11]
Hi

My fork of your repository is rewritten as a node-artifact and do not need any Dockerfile. However, my GitHub workflow fails when using the node-branch (I also tried the master branch with docker). The failure is caused by the folder node_modules being ignored: https://github.com/jactor-rises/add-and-commit/runs/345587672

Is this a suspected failure and has something todo with the default pattern?

**Comment by jactor-rises** [comment]
I am also getting a failure on another project using add-and-commit. https://github.com/navikt/bidrag-dokument-dto/commit/7061699a8b6b5d930877b40ef6840941ef492a3c/checks?check_suite_id=355151616 This failure do not occur when using the docker image. I see that the docker image is built from a git image and I would suspect that this image can do more than a normal Linux image.

Is this because of `cat <<- EOF > $HOME/.netrc`?

**Comment by EndBug** [comment]
Sorry, could you please keep the issues relative to your fork on your fork? (You can mention me there ;))
Anyway:

1. You should try using the `force` option, it should add even ignored files.
2. It may be: the Docker Image uses Alpine (from [this](https://hub.docker.com/r/alpine/git/) container) while your run probably uses Ubuntu. I'm not sure though, you should check the errors and see which part of the code fails.
