### ISSUE TITLE
Change how Github token is retrieved

### ISSUE THREAD

**Issue by Cyberbeni** [EndBug/add-and-commit#110]
It works fine for me without the token: https://github.com/Cyberbeni/ShowTouches/runs/1579363839?check_suite_focus=true#step:5:63

There is also this similar action that gets GITHUB_TOKEN like this: https://github.com/peter-evans/create-pull-request/blob/master/action.yml#L4-L6

Edit: it works without the token because I checked out the repo before and that also got the token the same way as the other action: https://github.com/actions/checkout/blob/main/action.yml#L12-L24

**Comment by EndBug** [comment]
Hi, thanks for the issue. I've actually noticed this too, but didn't think about it too much.
It's would be a good idea to get the token as that action does

**Comment by EndBug** [comment]
The fix has been included in `v6.1.0` (also `v6` and `latest`), thanks ❤️
