### ISSUE TITLE
"Used by" badge in the readme doesn't work as expected anymore

### ISSUE THREAD

**Issue by Cyberbeni** [EndBug/add-and-commit#113]
It currently only shows 3 results where "EndBug" is spelled all lowercase

**Comment by EndBug** [comment]
Thanks for the heads up! It seems like GitHub has changed how the search behaves with the `/` character: it seems like using `EndBug add-and-commit` works, I'll need to update my API though.
"Fixed" search: [`EndBug add-and-commit path:.github/workflows language:YAML`](https://github.com/search?o=desc&q=EndBug+add-and-commit+path%3A.github%2Fworkflows+language%3AYAML&s=&type=Code)

**Comment by EndBug** [comment]
Fixed (both for this repo and every other use of the API), no major changes involved
Thanks for reporting it :)
