### ISSUE TITLE
How can I make the author be github-actions?

### ISSUE THREAD

**Issue by Somfic** [EndBug/add-and-commit#121]
Is it possible to have the commit be authored by the bot account of GitHub?

I've tried actions@github.com with username github-action but it didn't quite work.

**Comment by EndBug** [comment]
What do you mean by "it doesn't quite work"? Does it mean that it shows those email and username but the picture is not right, or that it just keeps showing your profile?

Please also send a link to the action run you're referring to or, if in a private repo, a copy of the **entire** log from the step that uses this action.

**Comment by Somfic** [comment]
I was able to get it working with

```yml
author_name: github-actions[bot]
author_email: github-actions[bot]@users.noreply.github.com
```
