### ISSUE TITLE
Don't request the API if author_name and author_email are set

### ISSUE THREAD

**Issue by ocean90** [EndBug/add-and-commit#126]
I might be missing something but I think there's no need to request the GitHub API if both `author_name` and `author_email`  inputs are set?

https://github.com/EndBug/add-and-commit/blob/941a2d657a8dfe67f4671c065f53f3a6200ecfa5/src/main.ts#L229-L258

**Comment by EndBug** [comment]
I think you're right, thanks!

**Comment by EndBug** [comment]
@all-contributors please add @ocean90 for their idea
