### ISSUE TITLE
Using without pull / remote tracking

### ISSUE THREAD

**Issue by icehaunter** [EndBug/add-and-commit#138]
Hello, thanks for the action!

I'd like to use your action to force-push built documentation into the `gh-pages` branch. I don't need to pull the previous version, I just want to push the latest one. 

Is there a way to skip pull action altogether? Thanks in advance!

**Comment by EndBug** [comment]
No, currently there's no way to skip the pull command, but there should be! I'll try to add it as soon as I can 👍🏻

**Comment by EndBug** [comment]
Hi, sorry if this took so long.
I've added the future in the `no-pull` branch: try to see if using `EndBug/add-and-commit@no-pull` solves your problem. If it does, I'll publish it as a new minor version.

**Comment by exequiel09** [comment]
Would like this one get in also. Would love to have that option.

**Comment by EndBug** [comment]
@exequiel09 Have you tried using the `no-pull` option branch, as I suggested to the author of this issue? If that works for you I can release it

**Comment by mdreizin** [comment]
@EndBug I have tested and it works for me. Thanks!

**Comment by EndBug** [comment]
There you go: you can use the new `v7.1.0` release (also via `v7` and `latest`)

**Comment by mdreizin** [comment]
@EndBug Thank you!
