### ISSUE TITLE
v2.3.3 appears to be broken

### ISSUE THREAD

**Issue by jhhughes** [EndBug/add-and-commit#16]
Hi,

The latest update, v2.3.3, appears to have broken the action from the previous version as I am now seeing this in my workflow log instead of changes being committed:

``` Creating branch...
Switching branch...
Switched to branch 'master'
M	addon/install.rdf
M	updates.json
Pulling from remote...
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```

Also, it does not cause the workflow step to error either so the workflow appears to have completed successfully even though the changes were not applied back to the remote/master

Pinning to v2.3.2 has the step working perfectly fine once again (and has stopped me pulling my hair out thinking it was something I'd done seeing as I'm new to github workflows ;-p )

**Comment by EndBug** [comment]
That is weird, could you give me the link to the repo?
What version of `actions/checkout` are you using?

**Comment by jhhughes** [comment]
Ok, I've made https://github.com/jhhughes/ghtesting public now (only a workflow testi ground)

It is currenty using actions/checkout@v1

**Comment by jhhughes** [comment]
Ok, I ran a some tests:

- v2.3.2 with checkout@v1 - works
- v2.3.2 with checkout@v2 - works
- v2.3.3 with checkout@v1 - fails
- v2.3.3 with checkout@v2 - works

**Comment by EndBug** [comment]
Ok, I get what's the problem: I made the action while I was testing it with `actions/checkout@v2` and so I didn't see this issue. I will delete this release and publish it as v3.0.0 as soon as possible.
Thank you for reporting it to me :)

**Comment by EndBug** [comment]
@all-contributors please add @jhhughes for bug
