### ISSUE TITLE
Any way to use GitHub real name instead of username as the commit author?

### ISSUE THREAD

**Issue by ruohola** [EndBug/add-and-commit#167]
Currently if a workflow step doesn't specify `author_name`, and I trigger the workflow, the Git commit author will show up as:

```
ruohola <ruohola@users.noreply.github.com>
```

This is of course already **much** nicer than having it just be some random GitHub bot email, so this is not a massive issue.

But, I'm still wondering is there any way to make it instead be?

```
Eero Ruohola <ruohola@users.noreply.github.com>
```

(naturally without harcoding `author_name` since that would defeat the whole purpose)

This would be nice in Git logs where the author name would then match the name that is in my other commits as well.

**Comment by EndBug** [comment]
At the moment the action just uses the `github.actor` variable, but we could try to get the user's name with the GitHub API
Do you think that this should be done by default or that this should be opt-in, with a particular option?

**Comment by ruohola** [comment]
> At the moment the action just uses the `github.actor` variable, but we could try to get the user's name with the GitHub API
> Do you think that this should be done by default or that this should be opt-in, with a particular option?

Hard to say, I guess for not breaking anyone's existing flows a new boolean option would be best, where the deafult would be the existing behavior, e.g.

    real_name_as_commiter_name: false



This boolean would only have an effect when `auth_user` would be its default empty value.

**Comment by EndBug** [comment]
Another idea would be letting users use a placeholder like, idk, `actor_name`, and if that's the case the action will try to fetch the name of the GitHub actor

**Comment by ruohola** [comment]
Maybe the boolean would be less confusing.

**Comment by EndBug** [comment]
@all-contributors please add @ruohola for their idea

**Comment by EndBug** [comment]
Ok, I've added a `default_author` option that allows you to control how the action will fill missing author name and email. 
If you set it to `user_info` the action will use your display name and your actual email (if it's public) to create the commit.
Thanks again for your contribution! I'll publish it in the next minor version

**Comment by ruohola** [comment]
> Ok, I've added a `default_author` option that allows you to control how the action will fill missing author name and email.
> If you set it to `user_info` the action will use your display name and your actual email (if it's public) to create the commit.
> Thanks again for your contribution! I'll publish it in the next minor version

I think the email should still be the repo specific email though.

**Comment by EndBug** [comment]
Hmmm, why?
Also, it's not repo-specific, since that's the email you usually sign your commits with. Anyway, GitHub won't make any difference between one `user_info` and `github_actor`, you'll notice the difference just in the commit info

**Comment by ruohola** [comment]
> Hmmm, why?
> Also, it's not repo-specific, since that's the email you usually sign your commits with. Anyway, GitHub won't make any difference between one `user_info` and `github_actor`, you'll notice the difference just in the commit info

Oh right right, currently is just uses `<ruohola@users.noreply.github.com>` as the email.

**Comment by EndBug** [comment]
ℹ️ Feature published in `v7.2.0` (also `v7` and `latest`)

**Comment by suntong** [comment]
Why it is failing for me please?

![image](https://user-images.githubusercontent.com/422244/126543973-4991511a-ec3e-450a-8d69-69140fb3724a.png)

https://github.com/suntong/github_workflow/runs/3068857228?check_suite_focus=true

thanks!

**Comment by EndBug** [comment]
@suntong Looking at your profile (https://github.com/suntong), you don't have a public display name or email...

**Comment by suntong** [comment]
Ah, thanks @EndBug!
