### ISSUE TITLE
[Request] Add option to delete files

### ISSUE THREAD

**Issue by DmitrijOkeanij** [EndBug/add-and-commit#19]
I know that it can be cleared using command like this `- run: git rm delete_me.txt`. 
But syntax of this action is not full human understandable and need to know git commands.

Request is to add clear option. I think this simple action can close many issues and cases when needed to fully recreate destination folder/repository. And make code more simple and clear.

This is not functionality issue, but syntax and clean code.

PS: And documentation after that will be more simple too. No need big example of how to clean. Just one new option.

**Comment by EndBug** [comment]
It should be pretty simple: the option can be a string, that gets put in a `git rm` command.
To delete multiple files you should be able to put them in the same string, since `git rm file1 file2` works fine

**Comment by DmitrijOkeanij** [comment]
But if there is many files? In my case thee is more then 100 files.

**Comment by EndBug** [comment]
You can always use patterns as you would usually do on a `git add` or `git rm` command 😅

**Comment by EndBug** [comment]
This issue is resolved by version 3.1.0
