### ISSUE TITLE
Action fails for scheduled events

### ISSUE THREAD

**Issue by brahma-dev** [EndBug/add-and-commit#22]
Errors out for workflows using [Scheduled events](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule) at https://github.com/EndBug/add-and-commit/blob/master/src/main.ts#L15 since `eventPath` exists but not `head_commit`

**Comment by EndBug** [comment]
Hi, thanks for opening the issue!
Everything should be fixed in version [v4.0.1](https://github.com/EndBug/add-and-commit/releases/tag/v4.0.1)

**Comment by EndBug** [comment]
@all-contributors please add @brahma-dev for bug
