### ISSUE TITLE
[Wish] Send notice when repo updated

### ISSUE THREAD

**Issue by suntong** [EndBug/add-and-commit#245]
Most people using `add-and-commit` might indeed need to push changes to the repo, but I'm using `add-and-commit` from a `cron` job, which might or might not update the repo.

Thus, instead of me checking back if repo-updated happened or not each time, I'm thinking if there is an option to send me a notice (to my GH email) when the repo is in fact updated, that'll be great help for me. 

Don't know if it is possible, but logging it just in case. thx.

**Comment by EndBug** [comment]
Sending an email directly from the action to a mail address would require a working email account connected to the action, it'll be too complicated and probably used by far too few.

What you could do is using the GitHub notifications rss feed (which, if you watch the repo for "all activity", will include any pushes to the repo), and get notifications from that. I'm pretty sure you can use some tool to filter it and send notifications based on that.

**Comment by suntong** [comment]
Fair enough, 

watch the repo for "all activity", which will include any pushes to the repo

would be good enough for me. thx!

**Comment by suntong** [comment]
Oh, just double-checked it and found that watching for "all activity" doesn't work.

This is my ***default*** setting:
![image](https://user-images.githubusercontent.com/422244/126647677-7c63e0a2-f3dc-45d0-9aa5-1ddcf5de02e2.png)

and I didn't receive update for the following changes:
![image](https://user-images.githubusercontent.com/422244/126647776-9322fd50-8be0-4ff1-85b4-4fc87e8583f0.png)

Comment?

**Comment by suntong** [comment]
Ah, found it

- Please set some status flag whether check in has been made within the step.
- I'll access the flag in the next step to Send notification via https://github.com/marketplace/actions/send-push-notification#send-notification-using-schedule-trigger

**Comment by EndBug** [comment]
Seems like that action could do the trick!
You can use one of the action's [outputs](https://github.com/EndBug/add-and-commit#outputs) to determine whether you need to run the step that sends the notification.
Let me know if that works out.

**Comment by suntong** [comment]
Gotcha, thx!
