### ISSUE TITLE
Additional options for handling errors with Git Add

### ISSUE THREAD

**Issue by Glidias** [EndBug/add-and-commit#251]
Currently, a failure to git add a file (eg. due to typo/missing file, etc.) will gracefully fail according to the description at link: https://github.com/EndBug/add-and-commit#adding-files

"
The script will not stop if one of the git commands doesn't match any file. E.g.: if your command shows a "fatal: pathspec 'yourFile' did not match any files" error the action will go on.
"

Could there be options like exit immediately, or exit at the end with specific code of warning, etc?

**Comment by EndBug** [comment]
It could be added if it's needed. WHat would be your use case?

**Comment by Glidias** [comment]
Use case of Github actions (through pull requests and pushes) on Github appearing as a "Tick" despite having exceptions that occurred during the process of "building" stuff  within the action log. Though a more comprehensive version could involve having a file "strict" list or something, at a basic level maybe an option to specify "exitErrorImmediately" , "exitErrorAtEnd" or "noExit" could be done.

This happened due to a typo in the configuration listing out the built files to add/commit. So supposedly without a typo and without changing the filenames of built files (and forgetting to change the filenames for the action config as well), things would be fine for that case.

**Comment by EndBug** [comment]
@all-contributors please add @Glidias for their idea
