### ISSUE TITLE
add ´force´option

### ISSUE THREAD

**Issue by IvanVnucec** [EndBug/add-and-commit#252]
I have git ignored file but I want to commit it with add-and-commit action. The only solution to git adding ignored file is to append git add with --force attribute. Solution to this problem would be the option to force git add.

**Comment by EndBug** [comment]
From [the repo's README](https://github.com/EndBug/add-and-commit#adding-files):

> The action adds files using a regular `git add` command, so you can put every kind of argument in the add option. **For example, if you want to force-add a file: `./path/to/file.txt --force`**.

You can just add the `--force` argument in the input.

**Comment by IvanVnucec** [comment]
thank you
