### ISSUE TITLE
Error: Error: fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by maurineimirandazup** [EndBug/add-and-commit#281]
**Describe the bug**
Has an error already reported, I tried to use the proposed solutions and got no result.
`Error: Error: fatal: could not read Username for 'https://github.com': No such device or address`
Same: [#146](https://github.com/EndBug/add-and-commit/issues/146)
_Using the **actions/checkout@v2** and the problem persists._

**Workflow used**

https://github.com/maurineimirandazup/remote-build/actions/runs/1186532446/workflow

**Expected behavior**
Perform a commit and then generate a release.

**Logs**

https://github.com/maurineimirandazup/remote-build/runs/3474097407?check_suite_focus=true

<details>
  <summary>Logs</summary>
<pre><code>Run EndBug/add-and-commit@v5
  with:
    signoff: true
    message: Auto Build Formulas
    add: .
    cwd: .
    pull_strategy: --no-rebase
  env:
    GITHUB_TOKEN: ***
Running in /home/runner/work/remote-build/remote-build
> Using 'maurineimirandazup <maurinei.miranda@zup.com.br>' as author.
> Using "Auto Build Formulas" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
  > Found 57 changed files.
  Error: Error: fatal: could not read Username for 'https://github.com': No such device or address</code></pre>
</details>

**Comment by EndBug** [comment]
The job that `add-and-commit` is running in is not using `actions/checkout`. You have to run either `actions/checkout` or manual git commands in order to set up the repo with the required git credentials.

**Comment by maurineimirandazup** [comment]
First I would like to apologize for the open ISSUE.
I was desperate and didn't understand that there is a need checkout to get the credentials. 😅
Thanks for your attention!

**Comment by EndBug** [comment]
Don't worry, no problem! Glad to hear that you solved your issue 😄
