### ISSUE TITLE
Squash commit into previous one

### ISSUE THREAD

**Issue by barrettj12** [EndBug/add-and-commit#319]
I've got the Add & Commit action running on pushes and pull requests. So, suppose I push a sequence of commits
```
<commit_n>    <-- most recent
...
<commit_1>
```
to my repo. By default, Add & Commit will create a new commit at the top, so the commit history will look like:
```
Commit from GitHub Actions (<action name>)
<commit_n>
...
<commit_1>
```
However, I **don't want** this extra commit to be added - I want it to be squashed into the previous commit `<commit_n>`, so the commit history looks as it did originally. Is it possible to do this?

**Comment by EndBug** [comment]
It's not possible at the moment, but you can achieve this result by  running git commands
