### ISSUE TITLE
Ability to trigger "on push" actions

### ISSUE THREAD

**Issue by willhaines** [EndBug/add-and-commit#32]
I have a separate workflow that normally runs any time a change is pushed to the repo. It looks like this:

    on:
      push:
        branches:
          - master
        paths:
          - "**"

 I expected changes committed by EndBug/add-and-commit@v4 to trigger the same behavior, but they do not.

**Comment by EndBug** [comment]
Hi, I'm sorry, but that's just impossible: GitHub has made actions so that they can't trigger workflows, in order to avoid loops, and there's no way around this :(

The only thing you can do is setting up a second job in your workflow that waits for the first one to finish and then does the same things as the other one, which doesn't get triggered.

**Comment by TomasVotruba** [comment]
Hi, I have the same problem. I need to push, then trigger Github Actions again.

> The only thing you can do is setting up a second job in your workflow that waits for the first one to finish and then does the same things as the other one, which doesn't get triggered.

Could you share an example workflow code for this? I'd love to use it

**Comment by TomasVotruba** [comment]
Here is the pull-request: https://github.com/rectorphp/rector/pull/4492

The commit is pushed, but CI is *pending*.

![image](https://user-images.githubusercontent.com/924196/97324788-887a8000-1872-11eb-9f58-9f1b70b73fa6.png)


There could be 2 ways to handle this:

- make CI non-pending, it's been run once so no need to re-run - better
- trigger CI again

**Comment by TomasVotruba** [comment]
This might help, let's see how it goes:
[`0c6c794` (#4492)](https://github.com/rectorphp/rector/pull/4492/commits/0c6c794ac90e5aa192a2a88fd3c7f92fd05bb659)

**Comment by axelboc** [comment]
@TomasVotruba did it work?

**Comment by TomasVotruba** [comment]
I don't think so. Or only for repository owners. We need such feature for everybody.

Eventually we moved to pull-request actions:
https://github.com/TomasVotruba/tomasvotruba.com/blob/abbb28a4f7ccd9a6ef83840ce94c37f3ae9e1b50/.github/workflows/refresh_framework_stats.yaml#L43

Also it speeds up whole merge-request, as all the automated work is handled externally :+1:

**Comment by axelboc** [comment]
Oooh, very clever, thank you!!
