### ISSUE TITLE
Avoiding protected branches

### ISSUE THREAD

**Issue by JacekArdanowski** [EndBug/add-and-commit#340]
Hi,
I'd like to create a Github Action which will create and push a commit everytime a new release is created. Although the branch (`push: origin main`) I'm willing to push into is protected and needs at least 2 reviews (and some additional checks), so I receive the following message (also as an admin, I can push directly to main branch):
```
Error: Error: Pushing to https://github.com/corpadress/repo
POST git-receive-pack (686 bytes)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected. At least 2 approving reviews are required by reviewers with write access.
```
Can you provide me some hints on how to solve this issue?
I tried to provide my `author_name` and `author_email` for impersonating my admin rights, but it didn't really work.
Thanks

**Comment by arniesaha** [comment]
+1 Looking for answer for the same question.

Have added my user in the bypass section of the protected branch as well. Despite that doesn't seem to be impersonating my user to be able to make the commit to the protected branch

**Comment by EndBug** [comment]
Try checking out the repo using a [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (you have to add it your `actions/checkout` inputs).
The action pushes using the token with which the repository has been checked out, so maybe if you set a PAT GitHub will allow it to push the commit... I'm not sure though, let's just give it a try!

**Comment by JacekArdanowski** [comment]
Hi,
I made it work with below configuration:
``
- name: Checkout main repository
      uses: actions/checkout@v2
      with:
        token: _my_token_
        fetch-depth: 0
        
- name: Commit to source control
   uses: EndBug/add-and-commit@v7
   with:
        branch: main
        author_name: my_login
        author_email: my_login@mail.com
        push: origin main
``

Unfortunately this commit triggers CI as expected, so I guess it's a trade-off ;)

**Comment by arniesaha** [comment]
Thanks for the replies, folks! 

Yes using a pat works! :)

**Comment by EndBug** [comment]
Happy to see that it works!

> Unfortunately this commit triggers CI as expected, so I guess it's a trade-off ;)

I think you could avoid that by adding something to the commit that you later check for in the other workflows (like a "[auto]" prefix to the commit message, idk), and you make them proceed with CI only if that flag is not found...
It's not very elegant, but I guess that if you really needed to it would work. As you said, it's kind of a trade-off for authenticating as an actual user...

If everything's solved, feel free to close the issue ;)

**Comment by airtonix** [comment]
> Hi, I made it work with below configuration:
> 
> ```
> - name: Checkout main repository
>       uses: actions/checkout@v2
>       with:
>         token: _my_token_
>         fetch-depth: 0
>         
> - name: Commit to source control
>    uses: EndBug/add-and-commit@v7
>    with:
>         branch: main
>         author_name: my_login
>         author_email: my_login@mail.com
>         push: origin main
> ```
> 
> Unfortunately this commit triggers CI as expected, so I guess it's a trade-off ;)

make sure your commit message has `[skip ci]` in it.

**Comment by JacekArdanowski** [comment]
@airtonix Thank you for sharing this. I also include an article about this GitHub feature: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
