### ISSUE TITLE
Input that supports sign off

### ISSUE THREAD

**Issue by Namyalg** [EndBug/add-and-commit#360]
I wanted to know whether there is an input that supports sign off ?

**Comment by EndBug** [comment]
Yeah, there's the `commit` input. Thanks for pointing that out! It was added in v8.0.0 but I forgot to list it in the README 😓 
I'll fix this right away

**Comment by EndBug** [comment]
@all-contributors please add @Namyalg for their docs contibution

**Comment by Namyalg** [comment]
Thanks for the quick fix!
