### ISSUE TITLE
Commit failures should fail workflow

### ISSUE THREAD

**Issue by Josh-Cena** [EndBug/add-and-commit#370]
**Describe the bug**

If `git commit` fails, the workflow still completes despite nothing being pushed.

**Workflow used**

https://github.com/Josh-Cena/Josh-Cena.github.io/blob/master/.github/workflows/mark-non-coding-day.yml

**Expected behavior**

The workflow should exit with a non-zero status so GitHub would put a red cross.

**Logs**

https://github.com/Josh-Cena/Josh-Cena.github.io/runs/5408061374?check_suite_focus=true

**Comment by EndBug** [comment]
@all-contributors please add @Josh-Cena for their bug report

**Comment by Josh-Cena** [comment]
That's quick @EndBug Thanks!

(Didn't get time last week to test, but can confirm it works now!)
