### ISSUE TITLE
Is there a way to know if the push actually happened?

### ISSUE THREAD

**Issue by AqeelAT** [EndBug/add-and-commit#419]
If no files were updated, the commit would be empty and the push will say "Everything up-to-date".
Is there a way to capture that via step output?

For example, we have a workflow that lints the code then runs the test.
If the files were updated during the lint, we would push the changes and that would trigger another workflow run. However, I would like to exit the job early to not waste runner credits.

**Comment by EndBug** [comment]
Yup, you can use the `pushed` output. More info about this action's outputs [here](https://github.com/EndBug/add-and-commit#outputs)

**Comment by EndBug** [comment]
No, the outputs reflect what actually happened.
To get their value I'm using simple-git's callbacks, along with some additional logic for some of them. They're not just parsed from exit codes. If you try to run the action and use its output you'll see that when there are no changes your outputs will be like this:

```
committed: false
commit_long_sha: undefined
commit_sha: undefined
pushed: false
tagged: false
tag_pushed: false
```

If you want to see how it's actually done you can look at the source code but, unless there's any bug, the docs are up-to-date
Let me know if this solves your issue :)
