### ISSUE TITLE
Feature request: allow not fetching tags

### ISSUE THREAD

**Issue by Cireo** [EndBug/add-and-commit#422]
I have a repository with 25k tags.  Fetching all the tags takes over a minute, which would be convenient to skip.
The source indicates there is no such option available, since it is executed unconditionally.

**Comment by EndBug** [comment]
There is now! I've just published the feature in `v9.1.0` (also `v9` and `latest`)

**Comment by Cireo** [comment]
Awesome, grazie!

**Comment by Cireo** [comment]
NB: solved with same fix as https://github.com/EndBug/add-and-commit/issues/386, namely https://github.com/EndBug/add-and-commit/pull/423
