### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by coderaiser** [EndBug/add-and-commit#448]
**Describe the bug**

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Workflow used**

https://github.com/coderaiser/putout/actions/runs/3352929045/jobs/5555397923#step:11:325

**Expected behavior**
No warning shown.

**Comment by EndBug** [comment]
You're using an outdated version of `add-and-commit`
Please upgrade to `v9`, where this issue has already been fixed.
