### ISSUE TITLE
Not working in self hosted runner

### ISSUE THREAD

**Issue by amal-chandran** [EndBug/add-and-commit#465]
I have configured the add-and-commit in the workflow its was failing with the source code dump.

![image](https://user-images.githubusercontent.com/29562232/207228992-4f4ede5a-c1d4-445f-844c-63e687607813.png)

NodeJS: None
Ubuntu: Ubuntu 18.04.6 LTS
Runner Type: Self Hosted

**Comment by EndBug** [comment]
Hi, I need to have the workflow file you're using and the log of step that uses `add-and-commit`
