### ISSUE TITLE
Some way to manually change the author of the commit?

### ISSUE THREAD

**Issue by Cliffback** [EndBug/add-and-commit#466]
I have used this action to set up a workflow that automatically pushes submits from my Perforce server to my Github repo, only problem is that all of the commits now will be labeled as commited by me, even though we are multiple people working on it.

Is there some way to override the github_actor value to input a custom user, somehow?

I was thinking of making some kind of script comparing the username from the submit from perforce, and assigning the correct github user for the commit.

**Comment by EndBug** [comment]
Yeah, you can change both the author and the committer, check out [the Inputs section of the README](https://github.com/EndBug/add-and-commit#inputs).
