### ISSUE TITLE
Consider suggesting option `-A` to add and remove changed files

### ISSUE THREAD

**Issue by azeemba** [EndBug/add-and-commit#467]
The current documentation has a section on removing files. However, the documentation makes it sound like you have to know which files you want to remove in advance.

This doesn't have to be the case. The action already supports arbitrary arguments to `git add`. So [`-A`/`--no-ignore-removal`](https://git-scm.com/docs/git-add#Documentation/git-add.txt--A) can be used to ask git to commit any files that have been deleted in the local repository (just as it would have added any modified or new files).

I am happy to send a PR but I wanted to create an issue first to make sure my suggestion makes sense.

**Comment by EndBug** [comment]
Seems like a good idea! Yeah, it would be great if you could submit a PR ❤️
