### ISSUE TITLE
📄 Minor documentation discrepancy around default_author

### ISSUE THREAD

**Issue by keithrfung** [EndBug/add-and-commit#481]
# Documentation Fix
Small minor documentation fix around this section. Noticed a slight discrepency in the words vs the code.
https://github.com/EndBug/add-and-commit/blob/main/README.md#different-authorcommitter-configurations

## Original
>If you don't want to use your GitHub username for the CI commits, you can use the `default_author` option to make it appear as if it was made by "github-actions"

## FIxed
> If you don't want to use your GitHub username for the CI commits, you can use the `default_author` option to make it appear as if it was made by GitHub Actions by setting `github_actions`

**Comment by EndBug** [comment]
Thanks!

@all-contributors please add @keithrfung for their docs contribution
