### ISSUE TITLE
Warning: The set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by youn9k** [EndBug/add-and-commit#521]
<img width="1147" alt="image" src="https://github.com/EndBug/add-and-commit/assets/60254939/8d4e8a6a-c313-4be1-8ef9-0b8eeb7c06ff">

Document
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Similar issue
https://github.com/github/codeql-action/issues/1305

**Comment by EndBug** [comment]
Hi, it seems like you're using v7, this issue has been resolved in newer versions
You can check out the releases to see the breaking changes ;)
