### ISSUE TITLE
Failure to push isn't considered an error.

### ISSUE THREAD

**Issue by karliss** [EndBug/add-and-commit#53]
In case pushing changes fails (most likely due to incorrect permissions) the action and workflow is considered successful. 
I expected it to cause a failure.

```
  Tagging commit...
  Pushing commits to repo...
  remote: Permission to karliss/github-integration-test.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/karliss/github-integration-test/': The requested URL returned error: 403
  Pushing tags to repo...
  remote: Permission to karliss/github-integration-test.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/karliss/github-integration-test/': The requested URL returned error: 403
```

**Comment by EndBug** [comment]
Hi, thanks for the issue: this should be solved with the next re-write of the action. I can't give you an ETA for now

**Comment by EndBug** [comment]
Hi, I'd like you to test the rewrite to see if it properly fails when there's a push error.
To do that, please use `EndBug/add-and-commit@ts-only`
If everything's ok I'll merge it to the master branch and publish it as `v5`

**Comment by EndBug** [comment]
@bmartinez287 It doesn't seem to be relevant to this issue, let's move this conversation to a new one ;)
