### ISSUE TITLE
Default secret name is invalid

### ISSUE THREAD

**Issue by juancarlospaco** [EndBug/add-and-commit#54]
GitHub wont allow a Secret named `GITHUB_TOKEN`, it complains `Failed to add secret. Name is invalid`.

Then the action complains:
```
/Users/runner/work/_actions/EndBug/add-and-commit/v4/lib/entrypoint.sh: line 11: GITHUB_TOKEN: unbound variable

Pushing commits to repo...
  fatal: could not read Username for 'https://github.com': Device not configured
Pushing tags to repo...
  fatal: could not read Username for 'https://github.com': Device not configured
```

And it wont commit nor push.
Would be nice to change the default Secret name.

**Comment by EndBug** [comment]
The `GITHUB_TOKEN` doesn't need to be created, it's provided by GitHub to every workflow run, you just need to pass it as an env variable (as shown in the action docs)

If, however, you want to use a different token (for example, to push commits to a different repo) you can still pass it in the environment variables of the action step naming it `GITHUB_TOKEN`

If you have more questions please link the action step in your workflow

**Comment by juancarlospaco** [comment]
Oh, Ok.

**Comment by juancarlospaco** [comment]
So, I dont think is working, here I want the action to delete `*.c.o` files from a folder, and it Resets it back or not actually Push them at all,
here is the link to the GitHub Action, is bigger but basically is just an `rm *.c.o` and then should push that but wont work:

- https://github.com/juancarlospaco/faster-than-csv/runs/1045454157?check_suite_focus=true#step:19:178
- https://github.com/juancarlospaco/faster-than-csv/runs/1045454157?check_suite_focus=true#step:19:423
- `*.c.o` should be deleted https://github.com/juancarlospaco/faster-than-csv/tree/master/dist/lin
- YAML https://github.com/juancarlospaco/faster-than-csv/blob/master/.github/workflows/build.yml#L120-L125

:(

**Comment by EndBug** [comment]
You still are not passing any `GITHUB_TOKEN` env variable to the action. The README has everything you need to know about it.
Also, as I said in the previous comment, you can pass every other token, as long as there is a valid `GITHUB_TOKEN` env variable for the action to use.

**Comment by juancarlospaco** [comment]
Oh, ok, it works, that comment on the readme about the line should not be modified confused me.
