### ISSUE TITLE
Error with repository ownership

### ISSUE THREAD

**Issue by Eric-Jalal** [EndBug/add-and-commit#556]
With these arguments:
```yaml
  with:
    author_name: Github
    default_author: github_actor
    message: Convert new logos
    push: true
```

I'm getting this error:

```shell

Error: fatal: detected dubious ownership in repository at '/__w/my-repo-name/my-repo-name'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/my-repo-name/my-repo-name
```

And can I enter raw git commands in this step? or I have to make another step if the only way through this is to add that exception for this directory?

**Comment by EndBug** [comment]
Hey, how are you checking out the repo?
Can you share your workflow and logs?

**Comment by EndBug** [comment]
Can you share your workflow and/or a link to the action run?
I need to see how you are checking out the repo (so the step that calls `actions/checkout`, or the git commands you're using) to be able to help you
