### ISSUE TITLE
ref not working

### ISSUE THREAD

**Issue by honzajavorek** [EndBug/add-and-commit#56]
The docs:

```yaml
    # Name of the branch to use, if different from the one that triggered the workflow
    # Default: the branch that triggered the workflow (from GITHUB_REF)
    ref: 'someOtherBranch'
```

The reality:

```
##[warning]Unexpected input(s) 'ref', valid inputs are ['add', 'author_name', 'author_email', 'cwd', 'force', 'message', 'remove']
```

Also, I thought `ref` should be set to the branch I want the commit to be pushed, but reading the docs and the code, I'm not really sure what it's supposed to do. What I wanted is to push the change to a different branch than the one it's running on.

**Comment by honzajavorek** [comment]
Upgraded to 4.4.0 and it works 🤦

**Comment by TomasVotruba** [comment]
Hi @honzajavorek ,

I'm trying to figure out how to make pushing for pull-requests work, but struggle with remote branches/tokens. I'm new to this :)

How do you use this? Could you share link to Github Actoin file you're using it int?

**Comment by honzajavorek** [comment]
@TomasVotruba I'm using it [here](https://github.com/honzajavorek/film2trello/blob/master/.github/workflows/scripts.yml). The workflow gets triggered by cron, so it only runs on the main branch with correct credentials to push back to the repo, as the repo doesn't have any additional restrictions.

On a different repo I wanted to do a similar thing, but the repo has restrictions on who can commit and push to the main branch without reviews etc. It's [here](https://github.com/pyvec/docs.pyvec.org/blob/master/.github/workflows/generate_grants.yml). The script gets triggered by cron, but could not push back to the main branch just like that, because the branch is protected. There I don't use this @endbug's awesome reusable action, but [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request), so that the script automatically creates a Pull Request with the changes. The PR then needs to be manually reviewed, approved, and merged.

**Comment by TomasVotruba** [comment]
@honzajavorek I'll check the @peter-evans package, that might be exactly what I need. 
Thank you :+1:
