### ISSUE TITLE
Github errors when pushing a second PR

### ISSUE THREAD

**Issue by bmartinez287** [EndBug/add-and-commit#59]
It worked for the first PR I made but then it kept erroring out.

```
Run EndBug/add-and-commit@v4
Unable to get commit from workflow event: trying with the GitHub API...
Using 'Bernardo Martinez <bmartinez@demo.com>' as author.
Running for a PR, the action will use 'bmartinez287-particle' as ref.
Internal logs
error: failed to push some refs to 'https://github.com/UTCWeb/particle'
Task completed.
```

Here is the config file

`name: Node.js CI

```
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
```

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:drupal --if-present
    - run: npm run build:pl --if-present
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Bernardo Martinez
        author_email: bmartinez@demo.com
        message: "Compiling assets"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

**Comment by bmartinez287** [comment]
I'm not sure why it would after the first time. I try a bunch of different workarounds.

**Comment by EndBug** [comment]
Please add a link to the actual workflow run, so that I can see the "Internal logs" group. If this is a private repo, please copy the logs inside that group and post them here.

**Comment by EndBug** [comment]
Also, please reply to the other issue, since I'm going to push this fix to the ts rewrite anyway
