### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by mdboom** [EndBug/add-and-commit#613]
Thanks for `add-and-commit`!  It's been a really important part of [CPython's continuous benchmarking system](https://github.com/faster-cpython/benchmarking-public).

I am getting the following warnings from my Github actions:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: EndBug/add-and-commit@v9. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Are there plans to release a new version supporting Node 20 that would address this warning?

**Comment by EndBug** [comment]
Good catch! I'll do it ASAP ;)

**Comment by EndBug** [comment]
@all-contributors please add @mdboom for their maintenance contribution
