### ISSUE TITLE
ESling not found

### ISSUE THREAD

**Issue by moueza** [EndBug/add-and-commit#85]
Hi ! 
 I ve tried [your add with ESLint](https://github.com/moueza/youtube-comments-moueza/runs/1369939519?check_suite_focus=true) , but it says 
`Run eslint "**.html" --fix
/home/runner/work/_temp/bbd2754b-0c9c-4db7-8c11-3e0101871637.sh: line 1: eslint: command not found
Error: Process completed with exit code 127.`

Do you have an idea, please ?

**Comment by EndBug** [comment]
The step that uses my action is not even run: the error comes before.
I think that ESLint can't be found because you're running `npm install` but don't have any `package.json`, so you're not installing eslint at all.
Anyway, it's not a bug caused by the action.
