### ISSUE TITLE
Add the possibility NOT to push

### ISSUE THREAD

**Issue by kbsali** [EndBug/add-and-commit#86]
Hi,

thanks for this action, pretty handy.
I just have a little request : I have a use case where I run a series of tasks and on every step I would like to commit the changed/new files, but I only would like to push at the very end of the process. So in my case it would make sense to have an option to skip the `git push` on specific tasks.
What do you think?

**Comment by EndBug** [comment]
Hi, thanks for the issue! I've added the feature to the action: you'll now need to use the `push: false` option.
I'll publish this soon as a new minor version.

@all-contributors please add @kbsali for their idea

**Comment by EndBug** [comment]
Ok, I've published everything under version `v5.2.0` (also available via `v5` and `latest`)
Thank you again for the issue, I'll close it for now.

**Comment by kbsali** [comment]
awesome, thanks a lot @EndBug (and thank you twice for including me in the list of contributors... not sure it is deserved though! :sweat_smile: ) :+1:
