### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by Chocrates** [EndBug/add-and-commit#88]
Getting the below error when using the newest version `v5.1.1`
This has worked up until recently and rolling back to `v5.1.0` works great.
So far, going through the code I haven't been able to find the issue.
```
Run EndBug/add-and-commit@v5
Running in /home/runner/work/<repo>
> Unable to get commit from workflow event: trying with the GitHub API...
> Using 'Devops Bot <email>' as author.
> Using "Updating members.csv" as commit message.
Internal logs
Error: TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by EndBug** [comment]
HI, thanks for the issue!
Could you try to run it just once using the `master` branch as the ref? If using `master` works, then I'm pretty sure I know what's the problem.

**Comment by Chocrates** [comment]
Hey @EndBug looks like `master` works great!
What do you think the issue is?  For the morbidly curious 😄

**Comment by EndBug** [comment]
I think it was an issue with the build, that seems to be already solved ahahaha
I'll publish a patch to make sure that the correct build is released.

**Comment by EndBug** [comment]
Ok, I've published `v5.1.2` (also available via `v5` and `latest`). Could you check, one last time, if the action works with the last version?

**Comment by Chocrates** [comment]
@EndBug yep looks like that fixed it when I moved back to `v5` tag!
Thanks!

**Comment by EndBug** [comment]
Happy to hear that, I'll close the issue then.

**Comment by EndBug** [comment]
@all-contributors please add @Chocrates for bug
