### ISSUE TITLE
Commit all changed files?

### ISSUE THREAD

**Issue by yelizariev** [EndBug/add-and-commit#9]
As I understand the code below, using ``pattern: "*"`` will try to add files from ``.git`` repository

    else find $INPUT_PATH -name "$INPUT_PATTERN" | while read x; do git add $x; done

**Comment by EndBug** [comment]
If you use `"."` as path and `"*"` as pattern then it should also match files from the `.git` directory, but only if it's not ignored by any local or global config file (like it usually is)

**Comment by yelizariev** [comment]
You are right

> The git add command will not add ignored files by default. If any ignored files were explicitly specified on the command line, git add will fail with a list of ignored files. Ignored files reached by directory recursion or filename globbing performed by Git (quote your globs before the shell) will be silently ignored. The git add command can be used to add ignored files with the -f (force) option.

https://git-scm.com/docs/git-add
