### ISSUE TITLE
Add an output to let other steps know if something was pushed

### ISSUE THREAD

**Issue by ewjoachim** [EndBug/add-and-commit#96]
I'm a beginner in GH Actions, but if I understand it correctly, you could add an explicit output so that other tasks could run conditionnally based on whether this action pushed something or not.

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#outputs

**Comment by EndBug** [comment]
You're right, this could be useful. I'll add some outputs, not just this 👍🏻

**Comment by ewjoachim** [comment]
Yay thanks :) ❤️

**Comment by EndBug** [comment]
Hi, I've added 3 outputs to the actions: `committed`, `tagged`, and `pushed`. They're pretty self-explanatory, but there's more info on the README and in the action manifest.
I've published this change in `v5.3.0` (also accessible via `v5` and `latest`), feel free to test it and see if it fits your needs ;)

I'm closing this issue for now, feel free to contact me if you find any bug 👍🏻

**Comment by EndBug** [comment]
@all-contributors please add @ewjoachim for his idea

**Comment by ewjoachim** [comment]
Awww so sweet, thanks :)
