### ISSUE TITLE
Can't push to protected branch

### ISSUE THREAD

**Issue by bOmBeLq** [EndBug/add-and-commit#99]
May not be a bug but I can't figure it out. How do I grant access to action runner to be able to push to protected branch?
What's interesting is that error indicates it's pull request which it is not.
**Describe the bug**
So if branch has any of given protections:
- Require pull request reviews before merging
- Status checks found in the last week for this repository
it fails to push the changes.

**Workflow used**
```      - name: Fix code style
        run: ./docker.sh vendor/bin/php-cs-fixer fix
      - name: Commit fixes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: '[auto] php-cs-fixer'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
To push the changes

**Logs**
  > Pushing commit to repo...
  Error: Error: Pushing to XXXX
  POST git-receive-pack (683 bytes)
  remote: error: GH006: Protected branch update failed for refs/heads/master.        
  remote: error: At least 1 approving review is required by reviewers with write access.        
  error: failed to push some refs to XXXX

**Comment by EndBug** [comment]
Hi
I'm not sure, but I think you would need to authenticate with a personal token and exclude your repo administrators (I assume you're one of them) from the branch protection rule that's preventing the push.
That should work, but I have no way to test it right now and requires you to give up on the branch protection for admins.

**Comment by tomtom94** [comment]
Same error for me
